import { MobxStorageProtector } from "@/api/storage/db.protector"
import { MobxStorageProvider } from "@/api/storage/db.provider"
import type { Metadata } from "next"
import { Inter, Pacifico, Fira_Code, Source_Code_Pro } from "next/font/google"

import { Toaster } from "@/components/ui/sonner"
import "./globals.css"
import { NextThemeProvider } from "@/providers/theme/theme.provider"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const borel = Pacifico({
	subsets: ["latin"],
	weight: "400",
	variable: "--borel",
})

const sourceCodeFont = Source_Code_Pro({
	subsets: ["latin"],
	weight: ["400", "500"],
	variable: "--sourcecode-font",
})

const firacodeFont = Fira_Code({
	subsets: ["latin"],
	weight: ["400", "500"],
	variable: "--fira-font",
})
const rootFont = Inter({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "800", "900"],
	variable: "--root-font",
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${rootFont.className} ${rootFont.variable} ${borel.variable} ${sourceCodeFont.variable} ${firacodeFont.variable} antialiased`}
			>
				<NextThemeProvider>
					<MobxStorageProvider>
						<MobxStorageProtector>{children}</MobxStorageProtector>
					</MobxStorageProvider>
				</NextThemeProvider>
			</body>
		</html>
	)
}
