import { MobxStorageProtector } from '@/api/storage/db.protector'
import { MobxStorageProvider } from '@/api/storage/db.provider'
import type { Metadata } from 'next'
import { ViewTransitions } from 'next-view-transitions'
import { Borel, Poppins } from 'next/font/google'

import { Toaster } from '@/components/ui/sonner'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const borel = Borel({
	subsets: ['latin-ext'],
	weight: '400',
	variable: '--borel',
})
const rootFont = Poppins({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700', '800', '900'],
	variable: '--root-font',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ViewTransitions>
			<html lang='en'>
				<body
					className={`${rootFont.className} ${rootFont.variable} ${borel.variable} antialiased bg-light`}
				>
					<MobxStorageProvider>
						<MobxStorageProtector>{children}</MobxStorageProtector>
					</MobxStorageProvider>
					<Toaster />
				</body>
			</html>
		</ViewTransitions>
	)
}
